name: pedia_actual
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Ajustado para máxima compatibilidad con paquetes estables

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # --- GESTIÓN DE ESTADO & ARQUITECTURA ---
  flutter_bloc: ^9.1.1      # Para manejar los eventos y estados de la agenda
  equatable: ^2.0.5         # Necesario para comparar las entidades y estados en el Bloc

  # --- INYECCIÓN DE DEPENDENCIAS ---
  get_it: ^9.2.1            # Service Locator para enlazar las capas de Clean Architecture

  # --- GOOGLE FIREBASE ---
  firebase_core: ^4.10.0    # Inicialización obligatoria de Firebase
  cloud_firestore: ^6.5.0  # Base de datos NoSQL para las citas e historias médicas
  table_calendar: ^3.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  firebase_auth: ^6.5.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true