// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBum7TqgWB_N68utDDx4eXVYf1IbrnUgWI',
    appId: '1:262597705275:web:c95d8d8ad663fc85d8a61e',
    messagingSenderId: '262597705275',
    projectId: 'pediactual-ee23b',
    authDomain: 'pediactual-ee23b.firebaseapp.com',
    storageBucket: 'pediactual-ee23b.firebasestorage.app',
    measurementId: 'G-W4HB0Z8MBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiyC6Q-SKvEHjDIbLNU9QNfXeme5W0VJw',
    appId: '1:262597705275:android:acd67589b0dc9187d8a61e',
    messagingSenderId: '262597705275',
    projectId: 'pediactual-ee23b',
    storageBucket: 'pediactual-ee23b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9bjpoL-BR6SZEDlBArLET8Xu68VVhy8M',
    appId: '1:262597705275:ios:9dff5a052a13a6e8d8a61e',
    messagingSenderId: '262597705275',
    projectId: 'pediactual-ee23b',
    storageBucket: 'pediactual-ee23b.firebasestorage.app',
    iosBundleId: 'com.example.pediaActual',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9bjpoL-BR6SZEDlBArLET8Xu68VVhy8M',
    appId: '1:262597705275:ios:9dff5a052a13a6e8d8a61e',
    messagingSenderId: '262597705275',
    projectId: 'pediactual-ee23b',
    storageBucket: 'pediactual-ee23b.firebasestorage.app',
    iosBundleId: 'com.example.pediaActual',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBum7TqgWB_N68utDDx4eXVYf1IbrnUgWI',
    appId: '1:262597705275:web:245c3355df4b71d3d8a61e',
    messagingSenderId: '262597705275',
    projectId: 'pediactual-ee23b',
    authDomain: 'pediactual-ee23b.firebaseapp.com',
    storageBucket: 'pediactual-ee23b.firebasestorage.app',
    measurementId: 'G-3BP56919NW',
  );

}